import Head from 'next/head'
import { ReactNode, useEffect } from 'react'
import { LayoutNotApp } from 'src/views/layouts/LayoutNotApp'
import HomePage from 'src/views/layouts/pages/home'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce-NextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>

Home.guestGuard = false
Home.authGuard = false
