'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import CustomTextField from 'src/components/text-field'
import { Box } from '@mui/material'
import { ReactElement } from 'react'
import { LayoutNotApp } from 'src/views/layouts/LayoutNotApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce-NextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

Home.getLayout = (page: ReactElement) => <LayoutNotApp>{page}</LayoutNotApp>
